spring:
  profiles:
    active: @activatedProperties@
  application:
    name: eureka-server-high

prod:
  host1: localhost
  host2: localhost
  host3: localhost
  dev1Port: 8111
  dev2Port: 8112
  dev3Port: 8113
