spring:
  profiles:
    active: @activatedProperties@
  application:
    name: eureka-server-high
prod:
  host1: eurekav1.default.svc.cluster.local
  host2: eurekav2.default.svc.cluster.local
  host3: eurekav3.default.svc.cluster.local
  dev1Port: 8111
  dev2Port: 8112
  dev3Port: 8113
